services:
  web-api:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_ENVIRONMENT}
    ports:
      - "${EXPOSE_PORT_HTTP}:80"
      - "${EXPOSE_PORT_HTTPS}:443"
    restart: always
